#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Sensor, in2,    AccelXx,        sensorAccelerometer)
#pragma config(Sensor, in3,    AccelYy,        sensorAccelerometer)
#pragma config(Sensor, in4,    Pexpander,      sensorAnalog)
#pragma config(Sensor, in5,    LineLeft,       sensorLineFollower)
#pragma config(Sensor, in6,    LineRight,      sensorLineFollower)
#pragma config(Sensor, in7,    LineMiddle,     sensorLineFollower)
#pragma config(Sensor, in8,    LineOffest,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  TAC,            sensorDigitalIn)
#pragma config(Sensor, dgtl2,  ENCR,           sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  arduino1,       sensorDigitalOut)
#pragma config(Sensor, dgtl5,  arduino2,       sensorDigitalOut)
#pragma config(Sensor, dgtl6,  SONAR,          sensorSONAR_inch)
#pragma config(Sensor, dgtl8,  IR1,            sensorDigitalIn)
#pragma config(Sensor, dgtl9,  IR2,            sensorDigitalIn)
#pragma config(Sensor, dgtl10, IR3,            sensorDigitalIn)
#pragma config(Sensor, dgtl11, IR4,            sensorDigitalIn)
#pragma config(Sensor, dgtl12, solenoid,       sensorDigitalOut)
#pragma config(Motor,  port1,           feeder,        tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           Left1,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           Left2,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           Left3,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           m1,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           m2,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           Right1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           Right2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           Right3,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          Intake,        tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*----------------------------------------------------------------------------*/
/*                                                                            */
/*    Module:     main.c                                                      */
/*    Author:     Jefferson Maldonado                                         */
/*    Created:    2 May 2016                                                  */
/*                                                                            */
/*    Copyright (c) VCAT Robotics 2016, All Rights Reserved                   */
/*                                                                            */
/*----------------------------------------------------------------------------*/
/*                                                                            */
/*    Licensed under the Apache License, Version 2.0 (the "License");         */
/*    you may not use this file except in compliance with the License.        */
/*    You may obtain a copy of the License at                                 */
/*                                                                            */
/*    http://www.apache.org/licenses/LICENSE-2.0                              */
/*                                                                            */
/*----------------------------------------------------------------------------*/
#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(45)
#pragma userControlDuration(75)
///////////////////////////ENABLE DEBUG MODE (IF TRUE SKIPS AUTO SELECTION AND RUNS DEBUG AUTO ONLY)
#define DEBUG 0

//////////////////////////////////GLOBAL VARIABLES

int alliance = 4;        //NECESSARY FOR AUTONOMOUS SELECTION (LCD)
int autonomousN = 5;     //NECESSARY FOR AUTONOMOUS SELECTION (LCD)
int stage = 1;           //NECESSARY FOR SMART FEEDER
int MoveCounter = 0;     //NECESSARY FOR MOVE WHILE LOOP
int FeederStatus = 0;    //NECESSARY FOR SMART FEEDER
int BallCounter = 0;     //NECESSARY FOR BALL COUNTER TASK
int FailSafeEngaged = 0; //ENGAGED IF PROBLEM DURING MOVEMENT STEP
int CurrentSpeed = 0;    //CURRENT RPM
int TargetSpeed = 0;     //TARGET RPM
int ShootingMode = 4;    //FULL COURT - MID - BAR
int BasePower = 30;      //INITIAL MOTOR POWER
int rpmError = 0;        //ERROR CALCULATION

//////////////////////////////////INCLUDED FILES

#include "vex.c"            //VEX REQUIRED FILE
#include "Tasks.c"          //RPM CALC // RPM CONTROL // BALL COUNTER
#include "BasicMovements.c" //ALL FUNCTIONS
#include "BlueAuto1.c"      //BLUE AUTONOMOUS 1
#include "BlueAuto2.c"		  //BLUE AUTONOMOUS 2
#include "BlueAuto3.c"		  //BLUE AUTONOMOUS 3
#include "BlueAuto4.c"		  //BLUE AUTONOMOUS 4
#include "BlueAuto5.c"			//BLUE AUTONOMOUS 5
#include "RedAuto1.c"				//RED AUTONOMOUS 1
#include "RedAuto2.c"				//RED AUTONOMOUS 2
#include "RedAuto3.c"				//RED AUTONOMOUS 3
#include "RedAuto4.c"				//RED AUTONOMOUS 4
#include "RedAuto5.c"				//RED AUTONOMOUS 5
#include "SelfCheckCode.c"  //PRE AND POST MATCH AUTO TO CHECK SENSORS AND MOTORS
#include "DebugCode.c" 			//RUNS THIS AUTO IF DEBUG FLAG IS SET TO TRUE

///////////////////////////////////////////////////BEGIN PREAUTONOMOUS

void pre_auton()
{
#include "PreAuto.c"  			//GYRO CALIBRATION AND AUTONOMOUS SELECTION
}

///////////////////////////////////////////////////BEGIN AUTONOMOUS

task autonomous()
{
#include "Auto.c" 					//RUNS SELECTED AUTONOMOUS
}

///////////////////////////////////////////////////BEGIN DRIVER CONTROL

task usercontrol()
{
#include "DriverControl.c"	//RUNS DRIVER CONTROL CODE
}
